config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "products#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  resources :pictures
  resources :categories, only: [:show]
  resources :products do
    resources :bids, only: [:create, :index]
    resources :auto_bids, only: [:create]
    member do
      get 'detail'
      post 'buynow', to: 'products#buynow'
    end
  end

  resources :bids, only: [:show]

  resources :wishlists, only: [:show, :create] do
    collection do
      delete 'destroy'
    end
  end

  resources :users do
    collection do
      get 'profile'
      get 'wishlist'
    end
    member do
      post 'contact'
    end
  end


  resources :orders, only: [:index]

  resources :carts do
    collection do
      get 'address'
      get 'delivery'
      get 'review'
      get 'confirm'
      post 'success'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bids, class_name: "Bid", foreign_key: "buyer_id"
  has_many :orders, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :products, foreign_key: "seller_id", dependent: :destroy
  
  before_create :create_username

  private
    def create_username
      self.username = self.email.split("@")[0]
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  layout "authenticate"
  skip_before_action :get_main_info
  
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout "authenticate"
  skip_before_action :get_main_info
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "authenticate"
  skip_before_action :get_main_info
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :full_name,
                                 :street_addr, :city, :district, :zip_code,
                                 :phone, :country, :account_type)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "authenticate"
  skip_before_action :get_main_info
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:contact]
  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = current_user
    render 'show'
  end

  def wishlist
    @user = current_user
    @wishlists = current_user.wishlists
    render 'wishlist'
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(edit_user_params)
      redirect_to edit_user_path @user
    else
      redirect_to edit_user_path @user, alert: @user.errors.full_messages      
    end
  end

  def contact
    user = User.find_by(id: params[:id])
    message = params[:question]
    b = request.url.split("/")
    product = Product.find(b[b.length - 2])
    UserMailer.contact(user, current_user, message, product).deliver
    head 200
  end

  private
    def edit_user_params
      params.require(:user).permit(:username, :full_name,
                                    :street_addr, :city,
                                    :district, :zip_code,
                                    :country, :phone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_link = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_link, alt: user.name, class: "gravatar")
  end

  def gravatar_link(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_link = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_sidebar.html.erb
 <div class="customer-sidebar col-xl-3 col-lg-4 mb-md-5">
  <div class="customer-profile">
    <a href="#" class="d-inline-block">
      <img src="<%= gravatar_link(@user, size: 200) %>" class="img-fluid rounded-circle customer-image">
    </a>
    <h5><%= @user.full_name ? @user.full_name : @user.email %></h5>
    <p class="text-muted text-small">
      <% if @user.city.present? %>      
        <%= @user.city %>
        <%= ", #{@user.country}" if @user.country.present? %>
      <% else %>
        <%= @user.country if @user.country.present? %>      
      <% end %>
    </p>
  </div>

  <nav class="list-group customer-nav">
    <%= link_to orders_path, class:" list-group-item 
                                     d-flex justify-content-between 
                                     align-items-center", id:"orders-nav" do %>
      <span>
        <span class="icon icon-bag"></span>
        Orders
      </span>
      <small class="badge badge-pill badge-purple"><%= @user.orders.length %></small>
    <% end %>
    
    <%= link_to user_path(@user), class:"list-group-item 
                                         d-flex justify-content-between 
                                         align-items-center", id:"profile-nav" do %>
      <span>
        <span class="icon icon-profile"></span>
        Profile
      </span>
    <% end %>
    
    <% if @user == current_user %>
      <%= link_to edit_user_path(@user), class:"list-group-item 
                                           d-flex justify-content-between 
                                           align-items-center", id:"edit-profile-nav" do %>
        <span>
          <span class="icon icon-profile"></span>
          Edit Profile
        </span>
      <% end %>  
    <% end %>

    <% if @user == current_user %>
      <%= link_to wishlist_users_path, class:"list-group-item 
                                           d-flex justify-content-between 
                                           align-items-center", id:"wishlist-nav" do %>
        <span>
          <span class="icon icon-heart"></span>
          Wishlist
        </span>
      <% end %>  
    <% end %>
    
    <%= link_to destroy_user_session_path, method: :delete, 
                class:"list-group-item d-flex 
                justify-content-between 
                align-items-center" do %>
      <span>
        <span class="fa fa-sign-out"></span>
        Log out
      </span>
    <% end %>
  </nav>
</div>

<script>
  var url = window.location.href.split('/');
  if(url.includes("orders"))
    $('#orders-nav').addClass("active")
  if(url.includes("profile"))
    $('#profile-nav').addClass("active")
  if(url.includes("wishlist"))
    $('#wishlist-nav').addClass("active")
  if(url.includes("users")) {
    if(url.includes("edit"))
      $('#edit-profile-nav').addClass("active")
    else
      $('#profile-nav').addClass("active");  
  }
</script>

app/views/users/edit.html.erb
<section class="hero hero-page gray-bg padding-small">
  <div class="container">
    <div class="row d-flex">
      <div class="col-lg-9 order-2 order-lg-1">
        <h1>Your profile</h1>
      </div>
      <div class="col-lg-3 text-right order-1 order-lg-2">
        <ul class="breadcrumb justify-content-lg-end">
          <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
          <li class="breadcrumb-item active">Your profile</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<section class="padding-small">
  <div class="container">
    <div class="row">
      <!-- Customer Sidebar-->
      <%= render 'sidebar' %>
      
      <div class="col-lg-8 col-xl-9 pl-lg-3">
        <div class="block-header mb-5">
          <h5>Edit personal details</h5>
        </div>
        <%= form_with model: current_user, class: "content-block" do |f| %>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :full_name, class:"form-label"%>
                <%= f.text_field :full_name, class:"form-control", placeholder: "Nguyễn Văn A" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :username, class:"form-label"%>
                <%= f.text_field :username, class:"form-control", placeholder: "khoahoctunhien" %>
              </div>
            </div>            
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :phone, class:"form-label"%>
                <%= f.text_field :phone, class:"form-control", placeholder: "09xxxxxxxx" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label "Street Address", class:"form-label"%>
                <%= f.text_field :street_addr, class:"form-control", placeholder: "227 Nguyễn Văn Cừ" %>
              </div>
            </div>
          </div>
          <!-- /.row-->
          <div class="row">
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :zip_code, class:"form-label"%>
                <%= f.number_field :zip_code, class:"form-control", placeholder: "748417" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :district, class:"form-label"%>
                <%= f.text_field :district, class:"form-control", placeholder: "5" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :city, class:"form-label"%>
                <%= f.text_field :city, class:"form-control", placeholder: "TP Hồ Chí Minh" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :country, class:"form-label"%>
                <%= f.text_field :country, class:"form-control", placeholder: "Việt Nam" %>
              </div>
            </div>
            <div class="col-sm-12 text-center">
              <button type="submit" class="btn btn-template"><i class="fa fa-save"></i>Save changes</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero hero-page gray-bg padding-small">
  <div class="container">
    <div class="row d-flex">
      <div class="col-lg-9 order-2 order-lg-1">
        <h1>Your profile</h1>
      </div>
      <div class="col-lg-3 text-right order-1 order-lg-2">
        <ul class="breadcrumb justify-content-lg-end">
          <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
          <li class="breadcrumb-item active">Your profile</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<section class="padding-small">
  <div class="container">
    <div class="row">
      <!-- Customer Sidebar-->
      <%= render 'sidebar' %>
      
      <div class="col-lg-8 col-xl-9 pl-lg-3">
        <div class="block-header mb-5">
          <h5>Edit personal details</h5>
        </div>
        <%= form_with model: current_user, class: "content-block" do |f| %>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :full_name, class:"form-label"%>
                <%= f.text_field :full_name, class:"form-control", placeholder: "Nguyễn Văn A" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :username, class:"form-label"%>
                <%= f.text_field :username, class:"form-control", placeholder: "khoahoctunhien" %>
              </div>
            </div>            
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :phone, class:"form-label"%>
                <%= f.text_field :phone, class:"form-control", placeholder: "09xxxxxxxx" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label "Street Address", class:"form-label"%>
                <%= f.text_field :street_addr, class:"form-control", placeholder: "227 Nguyễn Văn Cừ" %>
              </div>
            </div>
          </div>
          <!-- /.row-->
          <div class="row">
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :zip_code, class:"form-label"%>
                <%= f.number_field :zip_code, class:"form-control", placeholder: "748417" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :district, class:"form-label"%>
                <%= f.text_field :district, class:"form-control", placeholder: "5" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :city, class:"form-label"%>
                <%= f.text_field :city, class:"form-control", placeholder: "TP Hồ Chí Minh" %>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="form-group">
                <%= f.label :country, class:"form-label"%>
                <%= f.text_field :country, class:"form-control", placeholder: "Việt Nam" %>
              </div>
            </div>
            <div class="col-sm-12 text-center">
              <button type="submit" class="btn btn-template"><i class="fa fa-save"></i>Save changes</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/wishlist.html.erb
<section class="men-collection gray-bg">
  <div class="container">
    <header class="text-center">
      <h2 class="text-uppercase"><small>Hello <%= @user.full_name%></small>Your wishlist</h2>
    </header>
    <div class="row">
      <% @wishlists.each do |wishlist| %>
      <div class="col-xl-3 col-md-4 col-sm-6">
        <div class="product is-gray">
          <div class="image d-flex align-items-center justify-content-center">
            <% if wishlist.product.pictures.length > 0 %>
              <%= image_tag wishlist.product.pictures.first.image.url, class: "img-fluid" %>
            <% else %>
              <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hoodie-man-1.png" alt="product" class="img-fluid">
            <% end %>
            <div class="hover-overlay d-flex align-items-center justify-content-center">
              <div class="CTA d-flex align-items-center justify-content-center">
                <a href="#" class="add-to-cart">
                  <i class="fa fa-shopping-cart"></i>
                </a>
                <%= link_to detail_product_path(wishlist.product), class: "visit-product active" do %>
                  <i class="icon-search"></i>
                  View
                <% end %>
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view">
                  <i class="fa fa-arrows-alt"></i>
                </a>
              </div>
            </div>
          </div>
          <div class="title">
            <%= link_to detail_product_path(wishlist.product) do %>
              <h3 class="h6 text-uppercase no-margin-bottom"><%= wishlist.product.name %></h3>
            <% end %>
            <span class="price text-muted">
              <% if wishlist.product.price_for_buy %>
                  <% if wishlist.product.price_for_buy > 0 %>
                    $<%= wishlist.product.price_for_buy %>
                  <% else %>
                    Bid only
                  <% end %>
                <% end %>
              </span>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>