config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "products#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  resources :pictures
  resources :categories, only: [:show]
  resources :products do
    resources :bids, only: [:create, :index]
    resources :auto_bids, only: [:create]
    member do
      get 'detail'
      post 'buynow', to: 'products#buynow'
    end
  end

  resources :bids, only: [:show]

  resources :wishlists, only: [:show, :create] do
    collection do
      delete 'destroy'
    end
  end

  resources :users do
    collection do
      get 'profile'
      get 'wishlist'
    end
    member do
      post 'contact'
    end
  end


  resources :orders, only: [:index]

  resources :carts do
    collection do
      get 'address'
      get 'delivery'
      get 'review'
      get 'confirm'
      post 'success'
    end
  end

end

app/views/commons/_footer.html.erb
<footer class="main-footer">
  <!-- Service Block-->
  <div class="services-block">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 d-flex justify-content-center justify-content-lg-start">
          <div class="item d-flex align-items-center">
            <div class="icon"><i class="icon-truck"></i></div>
            <div class="text">
              <h6 class="no-margin text-uppercase">Free shipping &amp; return</h6><span>Free Shipping over $300</span>
            </div>
          </div>
        </div>
        <div class="col-lg-4 d-flex justify-content-center">
          <div class="item d-flex align-items-center">
            <div class="icon"><i class="icon-coin"></i></div>
            <div class="text">
              <h6 class="no-margin text-uppercase">Money back guarantee</h6><span>30 Days Money Back Guarantee</span>
            </div>
          </div>
        </div>
        <div class="col-lg-4 d-flex justify-content-center">
          <div class="item d-flex align-items-center">
            <div class="icon"><i class="icon-headphones"></i></div>
            <div class="text">
              <h6 class="no-margin text-uppercase">028-123-456</h6><span>24/7 Available Support</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Main Block -->
  <div class="main-block">
    <div class="container">
      <div class="row">
        <div class="info col-lg-4">
          <div class="logo">
          <%= image_tag 'footer.svg', class: "img-fluid logo-brand" %>
          <span class="text-bold text-white" >ODUNAUCTION</span>
          </div>
          <p>Thank you for choosing us today</p>
          <ul class="social-menu list-inline">
            <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fa fa-pinterest"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i class="fa fa-vimeo"></i></a></li>
          </ul>
        </div>
        <div class="site-links col-lg-2 col-md-6">
          <h5 class="text-uppercase">Categories</h5>
          <ul class="list-unstyled">
            <% @categories.each do |category| %>
              <li><%= link_to category.name.titlecase, category_path(category.name.downcase) %></li>
            <% end %>
          </ul>
        </div>
        <div class="site-links col-lg-2 col-md-6">
          <h5 class="text-uppercase">Customer</h5>
          <ul class="list-unstyled">
            <li> <a href="#">Login</a></li>
            <li> <a href="#">Register</a></li>
            <% if @user %>
            <li>
              <%= link_to "Wishlist", wishlist_users_path %>
            </li>
            <% end %>
            <li> <a href="#">Our Products</a></li>
            <li> <a href="#">Checkouts</a></li>
          </ul>
        </div>
        <div class="newsletter col-lg-4">
          <h5 class="text-uppercase">Daily Offers &amp; Discounts</h5>
          <p> Enter your email here to contact us</p>
          <form action="#" id="newsletter-form">
            <div class="form-group">
              <input type="email" name="subscribermail" placeholder="Your Email Address">
              <button type="submit"> <i class="fa fa-paper-plane"></i></button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row d-flex align-items-center">
        <div class="text col-md-6">
          <p>© 2018 | EC17-10 | All rights reserved.</p>
        </div>
        <div class="payment col-md-6 clearfix">
          <ul class="payment-list list-inline-item pull-right">
            <li class="list-inline-item"><img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/visa.svg" alt="..."></li>
            <li class="list-inline-item"><img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/mastercard.svg" alt="..."></li>
            <li class="list-inline-item"><img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/paypal.svg" alt="..."></li>
            <li class="list-inline-item"><img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/western-union.svg" alt="..."></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/commons/_header.html.erb
<header class="header">
  <!-- Tob Bar-->
  <div class="top-bar">
    <div class="container-fluid">
      <div class="row d-flex align-items-center">
        <div class="col-lg-6 hidden-lg-down text-col">
          <ul class="list-inline">
            <li class="list-inline-item">
            <i class="icon-telephone"></i>028-123-456</li>
            <li class="list-inline-item">Free shipping on orders over $300</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn">
          <i class="icon-close"></i>
        </div>
        <form action="/products">
          <div class="form-group">
            <input type="search" name="name" id="search" placeholder="What are you looking for?">
            <button type="submit" class="submit">
            <i class="icon-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="container-fluid">
      <!-- Navbar Header -->
      <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.svg', class: "img-fluid logo-brand" %>
      <strong class="text-bold ">ODUNAUCTION</strong>
      <% end %>
      <button type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
      class="navbar-toggler navbar-toggler-right">
      <i class="fa fa-bars"></i>
      </button>
      <!-- Navbar Collapse -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a href="/" class="nav-link active">Home</a>
          </li>
          <!-- Megamenu-->
          <li class="nav-item dropdown menu-large">
            <a href="#" data-toggle="dropdown" class="nav-link">
              Menu
              <i class="fa fa-angle-down"></i>
            </a>
            <div class="dropdown-menu megamenu">
              <div class="row">
                <div class="col-lg-9">
                  <div class="row">
                    <div class="col-lg-3">
                      <strong class="text-uppercase">Home</strong>
                      <ul class="list-unstyled">
                        <li>
                          <%= link_to 'Homepage', root_path %>
                        </li>
                      </ul>
                    </div>
                    <div class="col-lg-3">
                      <strong class="text-uppercase">Categories</strong>
                      <ul class="list-unstyled">
                        <% @categories.each do |category| %>
                          <li><%= link_to category.name.titlecase, category_path(category.name.downcase) %></li>
                        <% end %>
                      </ul>
                    </div>
                    <div class="col-lg-3">
                      <strong class="text-uppercase">Customer</strong>
                      <ul class="list-unstyled">
                        <li>
                          <%= link_to 'Orders', orders_path %>
                        </li>
                        <li>
                          <%= link_to 'Wishlist', wishlist_users_path %>
                        </li>
                        <li>
                          <%= link_to 'Profile', profile_users_path %>
                        </li>
                        <li>
                          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                        </li>
                      </ul>
                    </div>
                    <div class="col-lg-3">
                      <strong class="text-uppercase">Seller</strong>
                      <ul class="list-unstyled">
                        <li>
                          <%= link_to 'Start selling', new_product_path %>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="row services-block">
                    <div class="col-xl-3 col-lg-6 d-flex">
                      <div class="item d-flex align-items-center">
                        <div class="icon">
                          <i class="icon-truck text-purple"></i>
                        </div>
                        <div class="text">
                          <span class="text-uppercase">Free shipping &amp; return</span>
                          <small>Free Shipping over $300</small>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 d-flex">
                      <div class="item d-flex align-items-center">
                        <div class="icon">
                          <i class="icon-coin text-purple"></i>
                        </div>
                        <div class="text">
                          <span class="text-uppercase">Money back guarantee</span>
                          <small>30 Days Money Back</small>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 d-flex">
                      <div class="item d-flex align-items-center">
                        <div class="icon">
                          <i class="icon-headphones text-purple"></i>
                        </div>
                        <div class="text">
                          <span class="text-uppercase">028-123-456</span>
                          <small>24/7 Available Support</small>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 d-flex">
                      <div class="item d-flex align-items-center">
                        <div class="icon">
                          <i class="icon-secure-shield text-purple"></i>
                        </div>
                        <div class="text">
                          <span class="text-uppercase">Secure Payment</span>
                          <small>Secure Payment</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <div class="col-lg-3 text-center product-col hidden-lg-down">
                <span class="text-uppercase product-heading">Your last order</span>
                <% if  @orders.length > 0 %>
                  <%= link_to detail_product_path(@orders.last.product), class: "product-image"  do %>
                    <% if  @orders.last.product.pictures.first %>
                      <%= image_tag @orders.last.product.pictures.first.image.url, class: "img-fluid" %>
                    <% else %>
                      <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/shirt.png" alt="..." class="img-fluid">
                    <% end %>
                  <% end %>
                <h6 class="text-uppercase product-heading">
                <a href="detail.html"><%= @orders.last.product.name %></a>
                </h6>
                <strong class="price text-purple">$<%= @orders.last.amount %></strong>
                <% end %>
              </div>
            </div>
          </div>
        </li>
        <!-- /Megamenu end-->
      </ul>
      <div class="right-col d-flex align-items-lg-center flex-column flex-lg-row">
        <!-- Search Button-->
        <div class="search">
          <i class="icon-search"></i>
        </div>
        <!-- User Not Logged - link to login page-->
        <div class="user">
          <%= link_to profile_users_path, class: "user-link", id: "userdetails" do %>
          <i class="icon-profile"></i>
          <% end %>
        </div>
        <!-- Cart Dropdown-->
        <div class="cart dropdown show">
          <a id="cartdetails" href="https://example.com" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">
            <i class="icon-cart"></i>
            <% if @orders.length > 0 %>
              <div class="cart-no"><%= @orders.length %></div>
            <% else %>
              <div class="cart-no">0</div>
            <% end %>
          </a>
          <div aria-labelledby="cartdetails" class="dropdown-menu">
            <!-- cart item-->
            <div class="dropdown-item cart-product">
              <div class="d-flex align-items-center">
                <div class="details d-flex justify-content-between">
                  <div class="text">
                    <strong>Your orders: </strong>
                    <small>Quantity: <%= @orders.count %></small>
                    <% @orders.each_with_index do |order, i| %>
                      <% if i == 5 %>
                        ...
                        <% break %>
                      <% else %>
                      <div class="product-name">
                        <%= i + 1 %>. <%= order.product.name %>
                      </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <!-- total price-->
            <div class="dropdown-item total-price d-flex justify-content-between">
              <span>Total</span>
              <strong class="text-purple">$<%= @total %></strong>
            </div>
            <!-- call to actions-->
            <div class="dropdown-item">
              <%= link_to 'Checkout', address_carts_path, class: "btn btn-template form-control" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/commons/_notice.html.erb
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %></br>
  </div>
<% end %>