config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "products#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  resources :pictures
  resources :categories, only: [:show]
  resources :products do
    resources :bids, only: [:create, :index]
    resources :auto_bids, only: [:create]
    member do
      get 'detail'
      post 'buynow', to: 'products#buynow'
    end
  end

  resources :bids, only: [:show]

  resources :wishlists, only: [:show, :create] do
    collection do
      delete 'destroy'
    end
  end

  resources :users do
    collection do
      get 'profile'
      get 'wishlist'
    end
    member do
      post 'contact'
    end
  end


  resources :orders, only: [:index]

  resources :carts do
    collection do
      get 'address'
      get 'delivery'
      get 'review'
      get 'confirm'
      post 'success'
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def address
  end

  def delivery
  end

  def payment
  end

  def review
  end

  def confirm
  end

  def success
    if (params[:response][:payer][:status] == "VERIFIED")
      @orders = Order.get_unpaid(current_user)
      @orders.each do |order|
        order.update_attribute(:is_paid, true)
      end
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_order.html.erb
<div class="item row d-flex align-items-center">
  <div class="col-6">
    <div class="d-flex align-items-center">
      <% if order.product.pictures.first %>
        <%= image_tag order.product.pictures.first.image.url, class: "img-fluid" %>      
      <% else %>
        <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/shirt.png" alt="..." class="img-fluid">
      <% end %>
      <div class="title">
        <a href="detail.html">
          <h6><%= order.product.name %></h6></a>
      </div>
    </div>
  </div>
  <div class="col-4">
    <span><%= simple_format order.created_at.strftime("%d-%m-%y\n%H:%M:%S") %></span>
  </div>
  <div class="col-2"><span><%= order.amount %></span></div>
</div>

app/views/carts/_subheader.html.erb
<section class="hero hero-page gray-bg padding-small">
  <div class="container">
    <div class="row d-flex">
      <div class="col-lg-9 order-2 order-lg-1">
        <h1 class="text-capitalize"><%= request.url.split("/").last %></h1>
        <p class="lead">You currently have <%= @orders.length %> item(s) in your basket</p>
      </div>
      <div class="col-lg-3 text-right order-1 order-lg-2">
        <ul class="breadcrumb justify-content-lg-end">
          <li class="breadcrumb-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="breadcrumb-item active text-capitalize"><%= request.url.split("/").last %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/carts/_summary.html.erb
<div class="block-body order-summary">
	<h6 class="text-uppercase">Order Summary</h6>
	<p>Shipping and additional costs are calculated based on values you have entered</p>
	<ul class="order-menu list-unstyled">
		<li class="d-flex justify-content-between"><span>Order Subtotal </span><strong>$<%= @total %></strong></li>
		<li class="d-flex justify-content-between"><span>Shipping and handling</span><strong>$0.00</strong></li>
		<li class="d-flex justify-content-between"><span>Tax</span><strong>$0.00</strong></li>
		<li class="d-flex justify-content-between"><span>Total</span><strong class="text-primary price-total">$<%= @total %></strong>
		</li>
	</ul>
</div>

app/views/carts/address.html.erb
<%= render partial: 'carts/subheader' %>
<section class="checkout">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <%= link_to 'Address', address_carts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item"><a href="#" class="nav-link disabled">Delivery Method </a></li>
          <li class="nav-item"><a href="#" class="nav-link disabled">Order Review</a></li>
        </ul>
        <div class="tab-content">
          <div id="address" class="active tab-block">
            <div class="block-header mb-5">
              <h6>Invoice address </h6>
            </div>
            <%= form_with model: current_user, class: "content-block" do |f| %>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :full_name, class:"form-label"%>
                  <%= f.text_field :full_name, class:"form-control", placeholder: "Nguyễn Văn A" %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :username, class:"form-label"%>
                  <%= f.text_field :username, class:"form-control", placeholder: "khoahoctunhien" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :phone, class:"form-label"%>
                  <%= f.text_field :phone, class:"form-control", placeholder: "09xxxxxxxx" %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label "Street Address", class:"form-label"%>
                  <%= f.text_field :street_addr, class:"form-control", placeholder: "227 Nguyễn Văn Cừ" %>
                </div>
              </div>
              <!-- /.row-->
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <%= f.label :zip_code, class:"form-label"%>
                  <%= f.number_field :zip_code, class:"form-control", placeholder: "748417" %>
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <%= f.label :district, class:"form-label"%>
                  <%= f.text_field :district, class:"form-control", placeholder: "5" %>
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <%= f.label :city, class:"form-label"%>
                  <%= f.text_field :city, class:"form-control", placeholder: "TP Hồ Chí Minh" %>
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <%= f.label :country, class:"form-label"%>
                  <%= f.text_field :country, class:"form-control", placeholder: "Việt Nam" %>
                </div>
              </div>
              <% end %>
            </div>
            <div>
              <%= link_to delivery_carts_path, class: "btn btn-template form-control next" do %>
              Choose delivery method
              <i class="fa fa-angle-right"></i>
              <% end %>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <%= render partial: 'carts/summary' %>
    </div>
  </div>
</div>
</section>

app/views/carts/confirm.html.erb
<%= render partial: 'carts/subheader' %>

<section class="checkout">
  <div class="container">
    <div class="confirmation-icon"><i class="fa fa-check"></i></div>
    <h2>Thank you, <%= current_user.full_name %>. Your order is confirmed.</h2>
    <p class="mb-5">Your order hasn't shipped yet but we will send you ane email when it does.</p>
    <p>
      <%= link_to 'View or manage your order', orders_path, class: "btn btn-template wide" %>
    </p>
  </div>
</section>

app/views/carts/delivery.html.erb
<%= render partial: 'carts/subheader' %>

<section class="checkout">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <%= link_to 'Address', address_carts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Delivery Method', delivery_carts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item"><a href="#" class="nav-link disabled">Order Review</a></li>
        </ul>
        <div class="tab-content">
          <div id="delivery-method" class="tab-block">
            <form action="#" class="shipping-form">
              <div class="row">
                <div class="form-group col-md-6">
                  <input type="radio" name="shippping" id="option1" class="radio-template">
                  <label for="option1"><strong>Usps next day</strong><br><span class="label-description">Get it right on next day - fastest option possible.</span></label>
                </div>
                <div class="form-group col-md-6">
                  <input type="radio" name="shippping" id="option2" class="radio-template">
                  <label for="option2"><strong>Usps next day</strong><br><span class="label-description">Get it right on next day - fastest option possible.</span></label>
                </div>
                <div class="form-group col-md-6">
                  <input type="radio" name="shippping" id="option3" class="radio-template">
                  <label for="option3"><strong>Usps next day</strong><br><span class="label-description">Get it right on next day - fastest option possible.</span></label>
                </div>
                <div class="form-group col-md-6">
                  <input type="radio" name="shippping" id="option4" class="radio-template">
                  <label for="option4"><strong>Usps next day</strong><br><span class="label-description">Get it right on next day - fastest option possible.</span></label>
                </div>
              </div>
            </form>
            <div class="CTAs d-flex justify-content-between flex-column flex-lg-row">
              <%= link_to address_carts_path, class: "btn btn-template-outlined wide prev" do %>
                <i class="fa fa-angle-left"></i>
                Back to Address
              <% end %>
              
              <%= link_to review_carts_path, class: "btn btn-template wide next" do %>
                Review your orders
                <i class="fa fa-angle-right"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <%= render partial: 'carts/summary' %>
      </div>
    </div>
  </div>
</section>

app/views/carts/review.html.erb
<%= render partial: 'carts/subheader' %>

<section class="checkout">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <%= link_to 'Address', address_carts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Delivery Method', delivery_carts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Order Review', review_carts_path, class: "nav-link active" %>
          </li>
        </ul>
        <div class="tab-content">
          <div id="order-review" class="tab-block">
            <div class="cart">
              <div class="cart-holder">
                <div class="basket-header">
                  <div class="row">
                    <div class="col-6">Product</div>
                    <div class="col-4">Buy at</div>
                    <div class="col-2">Price</div>
                  </div>
                </div>
                <div class="basket-body">
                  <!-- Product-->
                  <%= render partial: 'carts/order', collection: @orders, as: :order %>
                  <!-- Product-->
                </div>
              </div>
              <div class="total row"><span class="col-md-10 col-2">Total</span>
                <span class="col-md-2 col-10 text-primary">$<%= @total %></span></div>
            </div>
            <div class="CTAs d-flex justify-content-between flex-column flex-lg-row">
              <%= link_to delivery_carts_path, class: "btn btn-template-outlined wide prev" do %>
                <i class="fa fa-angle-left"></i>
                Back to delivery method
              <% end %>

              <div id="paypal-button"></div>
              
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="block-body order-summary">
          <h6 class="text-uppercase">Order Summary</h6>
          <p>Shipping and additional costs are calculated based on values you have entered</p>
          <ul class="order-menu list-unstyled">
            <li class="d-flex justify-content-between"><span>Order Subtotal </span><strong>$<%= @total %></strong></li>
            <li class="d-flex justify-content-between"><span>Shipping and handling</span><strong>$0.00</strong></li>
            <li class="d-flex justify-content-between"><span>Tax</span><strong>$0.00</strong></li>
            <li class="d-flex justify-content-between"><span>Total</span><strong class="text-primary price-total">$<%= @total %></strong></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  $(document).on('turbolinks:load', function() {
  if ($('#paypal-button').length > 0) {
    if ($(".paypal-button").length == 0 ) {
      paypal.Button.render({

      env: 'sandbox',

      commit: true,

      style: {
        label: 'paypal',
        size: 'medium', // small | medium | large | responsive
        shape: 'rect', // pill | rect
        color: 'blue', // gold | blue | silver | black
        tagline: false
      },

      client: {
        sandbox: "<%= ENV['PAYPAL_CLIENT_ID'] %>",
        production: '<insert production client id>'
      },

      payment: function(data, actions) {
        return actions.payment.create({
          payment: {
            transactions: [{
              amount: {
                total: "<%= @total %>",
                currency: 'USD'
              }
            }]
          }
        });
      },

      onAuthorize: function(data, actions) {
        return actions.payment.execute().then(function(res) {
          window.alert('Payment Complete!');
          $.ajax({
            type: "POST",
            url: "/carts/success",
            data: {
              response: res
            },
            dataType: "json"
          })
          .then(function() {
            window.location.href = '/carts/confirm';
          })
        });
      },

      onCancel: function(data, actions) {
        /* 
         * Buyer cancelled the payment 
         */
      },

      onError: function(err) {
        /* 
         * An error occurred during the transaction 
         */
      }

    }, '#paypal-button');
    } 
  }
  })
</script>