config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "products#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  resources :pictures
  resources :categories, only: [:show]
  resources :products do
    resources :bids, only: [:create, :index]
    resources :auto_bids, only: [:create]
    member do
      get 'detail'
      post 'buynow', to: 'products#buynow'
    end
  end

  resources :bids, only: [:show]

  resources :wishlists, only: [:show, :create] do
    collection do
      delete 'destroy'
    end
  end

  resources :users do
    collection do
      get 'profile'
      get 'wishlist'
    end
    member do
      post 'contact'
    end
  end


  resources :orders, only: [:index]

  resources :carts do
    collection do
      get 'address'
      get 'delivery'
      get 'review'
      get 'confirm'
      post 'success'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :pictures, :dependent => :destroy
  validates :name, presence: true
  validates :auction_price_start, presence: true

  validates :auction_price_start, numericality: { greater_than_or_equal: 0 }, :allow_nil => true
  validates :price_for_buy, numericality: { greater_than_or_equal: 0 }, :allow_nil => true

  has_many :bids, dependent: :destroy
  has_many :auto_bids, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  after_create :trigger_bidding_countdown
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  before_save :parse_timezone

  def parse_timezone
    if date_end_auction
      self.date_end_auction = date_end_auction - 7.hours
    end
  end
  
  def trigger_bidding_countdown
    if has_auction
      CheckWinnerJob.set(wait_until: date_end_auction).perform_later self
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_before_action :verify_authenticity_token
	def index
		if params[:name]
			@params = params[:name]
			@products = Product.where('name LIKE ?', "%#{params[:name]}%")
			render 'search'
		else
			@buynows = Product.where(has_buy_now: true)
			@auctions = Product.where(has_auction: true)
			@products = Product.all
			@user = current_user
			render 'index'
		end
	end

	def detail
		@product = Product.find(params[:id])
		@wishlist = Wishlist.find_by(product_id: @product.id, user_id: current_user)
		@bids = @product.bids.includes(:buyer).order(amount: :desc)
		@current_bid = @bids.first
		@products = Product.where.not(id: @product.id).where(cateid: @product.cateid).shuffle[0..3]
	end

	def new
		@product = Product.new
		@currentuser = current_user.id
		@category = Category.all
	end

	def show
    @product  = Product.find(params[:id])
    @pictures = @product.pictures
    @category= Category.find(@product.cateid)
    @seller = @product.seller

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

	def edit
		@product = Product.find(params[:id])
		@currentuser=current_user.id
		@category = Category.all

	end


	def create
		@product = Product.new(product_params)
		@product.seller = current_user
		if @product.save
			if params[:images]

		        params[:images].each { |image|
		          @product.pictures.create(image: image)
		        }
      		end
			redirect_to products_path
		else
			redirect_to new_product_path, alert: @product.errors.full_messages
		end
	end

	def update
		@product = Product.find(params[:id])
    	if @product.update_attributes(product_params)
	    	if params[:images]
	        params[:images].each { |image|
	          @product.pictures.create(image: image)
	        }
	      end
	    NotifyupdateproductMailer.sample_email(current_user).deliver
	    redirect_to products_path
	   else
	      redirect_to edit_product_path, alert: @product.errors.full_messages
	   end
	end

	def destroy
	  @product = Product.find(params[:id])
	  @product.destroy

	  respond_to do |format|
	    format.html { redirect_to root_path }
	    format.js
    	end
	end

	def buynow
		@order = Order.new
		@order.user = current_user
		@order.product = Product.find(params[:id])
		@order.amount = params[:amount]
		@order.is_paid = false
		if @order.save
			head 201
			UserMailer.buynow(@order).deliver
		else
			render json: { error: @order.errors.full_messages }, status: 403
		end
	end

	private
		def product_params
			params.require(:product).permit(:name, :condition,:has_auction,:has_buy_now,
			:pictures,:details,:price_for_buy,:date_end_auction,:description,:auction_price_start,:cateid)
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_bid.html.erb
<% if @product.has_auction == 1%>
<div>
  <div class="d-flex align-items-center justify-content-between flex-column flex-sm-row">
    <ul class="price list-inline no-margin">
        <% if @current_bid %>
          <li class="list-inline-item current">
            Current Bid: $ 
            <span id="current-bid-amount"><%= @current_bid.amount %></span>
          </li>
        <% else %>
          <li class="list-inline-item current">
            Current Bid: $ 
            <span id="current-bid-amount"><%= @product.auction_price_start %></span>
          </li>          
        <% end %>
    </ul>
  </div>
  <ul class="list-inline">
    <li class="list-inline-item current">
      <% if @product.date_end_auction <= Time.now.utc %>
        <span class="text-danger">Auction had been ended</span>
      <% else %>
        <span>Auction ended in: </span> <span id="clock" class="countdown"></span>      
      <% end %>
    </li>
  </ul>
  <ul class="row list-inline">
    <li class="list-inline-item col-6">
      <input type="number" step="0.01" class="form-control" 
             name="bid-amount" placeholder="Place bid"/>
    </li>
    <li class="list-inline-item">
      <button class="btn btn-template" id="submit-bid">Place bid</button>
    </li>
  </ul>
  <ul class="row list-inline">
    <li class="list-inline-item col-6">
      <input type="number" step="0.01" class="form-control" 
             name="auto-bid-amount" placeholder="Place maximum bid"/>
    </li>
    <li class="list-inline-item">
      <button class="btn btn-info" id="submit-auto-bid">Automate bid</button>
    </li>
  </ul>
  <div class="row">
    <p name="bid-errors" class="alert alert-danger col-8 hidden"></p>
  </div>
</div>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){
    $('#clock').countdown("<%= @product.date_end_auction %>", function(event) {
      var $this = $(this).html(event.strftime(' '
        + '<span>%d</span> days '
        + '<span>%H</span> hr '
        + '<span>%M</span> min '
        + '<span>%S</span> sec'));
    });
  })
</script>

app/views/products/_bid_history.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col" class="col-1">#</th>
      <th class="col-4">Bidder</th>
      <th class="col-2 text-right">Amount</th>
      <th class="col-5 text-right">Created At</th>
    </tr>
  </thead>
  <tbody>
    <% @bids.each_with_index do |bid, index| %>
      <tr>
        <td scope="row" class="col-1"><%= index + 1 %></td>
        <td class="col-4">
          <%= link_to bid.buyer.username, 
                      user_path(bid.buyer.id),
                      target: "_blank" %>
          <% if index == 0 %>
            <i class="fa fa-trophy color-gold"></i>
          <% end %>
        </td>
        <td class="col-2 text-right"><%= bid.amount %></td>
        <td class="col-5 text-right">
          <%= (bid.created_at + 7.hours).strftime("%Y-%m-%d %H:%M:%S") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/_contact.html.erb
<div>
  <strong>Seller: </strong>
  <%= link_to @product.seller.username, user_path(@product.seller.id) %>
</div>
<div class="row">
  <div class="col-8 form-group">
    <textarea rows="4" class="form-control" 
              placeholder="Ask a question"
              id="question"></textarea>
  </div>
   <div class="col-4 form-group">
    <button class=" form-control btn btn-primary" id="contact-seller">Send to seller</button>
  </div>
</div>

<script>
  $(document).on('turbolinks:load', function(){
    $('#contact-seller').click(function(e) {
      var question = $("#question").val();
      $.post("/users/<%= @product.seller.id %>/contact", {
        question: question
      }).then(function(){
        $(e.target).addClass("disabled")
        $(e.target).parent().parent()
        .append("<div class='col text-success'>Send to seller successfully.</div>")
      }).catch(function(){
        $(e.target).parent().parent()
        .html("<div class='col text-danger'>An error has occur.</div>")        
      })
    })
  })
</script>

app/views/products/_form.html.erb
	
	<style type="text/css">
		label{
			font-weight: bold;
		}
	</style>
	<%= form_with model: @product,:html => { :multipart => true } do |f|%>
		
		<%= f.hidden_field :seller,class: "form-control", :value=>@currentuser%>

		<div class="form-group">
			<label class="label-control">
				Name
			</label>
			<%= f.text_field :name,class: "form-control",required: "true", placeholder:"Xiaomi Redmi Note4x"%>

		</div>
		<div class="form-group">
			<label class="label-control">
				Category
			</label>
		

		<%= f.select :cateid, options_for_select(@category.map{ |c| [c.name, c.id, {'data-id'=>c.id}] }, selected_key = f.object.cateid) %>
		</div>
		
		<div class="form-group">
			<label class="label-control">
				Condition
			</label>
			<%= f.label :condition, "New", :value => "1"  %>
			    <%= f.radio_button :condition, "1" %>
			 <%= f.label :condition, "Old", :value => "0" %>
			    <%= f.radio_button :condition, "0" %>

		</div>

		<div  class="form-group">
			<label class="label-control">
				Has auction?
			</label>
			 	<%= f.label :has_auction, "Yes", :value => "1"  %>
			    <%= f.radio_button :has_auction, "1" %>
			    <%= f.label :has_auction, "No", :value => "0" %>
			    <%= f.radio_button :has_auction, "0" %>

		</div>
		<div id="auction_area" style="display: none">
			<div class="form-group">
				<label class="label-control">
					Start price
				</label>
				<%= f.number_field :auction_price_start,class: "form-control", placeholder:"20"%>

			</div>

			<div class="form-group">
				<label class="label-control">
					DateEndAuction
				</label>
				

            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    
                    <%= f.text_field :date_end_auction,class: "form-control",data: { date_format: 'YYYY/MM/DD HH:mm' } %>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

        

			</div>
		</div>
		<div class="form-group">
			<label class="label-control">
				Has buy now?
			</label>
			  
			    <%= f.label :has_buy_now, "Yes", :value => "1"  %>
			    <%= f.radio_button :has_buy_now, "1" %>
			    <%= f.label :has_buy_now, "No", :value => "0" %>
			    <%= f.radio_button :has_buy_now, "0" %>
		</div>
		<div id="buy_area" style="display: none">
			<div class="form-group">
				<label class="label-control">
					Price
				</label>
				<%= f.number_field :price_for_buy,class: "form-control", placeholder:"20"%>

			</div>
		</div>
		<div class="form-group">
			<label class="label-control">
				Description
			</label>
			<%= f.text_area :description,class: "form-control",required: "true", placeholder:"Xiaomi Redmi Note4x"%>

		</div>

		<div class="form-group">
			<label class="label-control">
				Details
			</label>
			<%=f.cktext_area :details,required: "true", id: 'details'%>


		</div>
		<div class="form-group">
			<%= f.label :pictures, :class => 'control-label' %>
			
			
		
			<%= file_field_tag "images[]", type: :file, accept: 'image/png,image/jpeg,image/jpg',multiple: true %>
		</div>



		<button type="submit" class="btn btn-primary">Create/Update</button>

		<div class="clearfix"></div>

		

	<% end%>

	<script>	
		$(document).ready(function()
		{

			$("input:radio[name='product[has_auction]']").change(function(){
			    if($(this).val() == '1'){
			       $('#auction_area').css("display","block");
   				}
   				else{
   					 $('#auction_area').css("display","none");
   				}
			});

			$("input:radio[name='product[has_buy_now]']").change(function(){
			    if($(this).val() == '1'){
			       $('#buy_area').css("display","block");
   				}
   				else{
 					$('#buy_area').css("display","none");
   				}
			});

			//for edit

			
			if($("input:radio[name='product[has_auction]']:checked").val()=='1')
			{
				 $('#auction_area').css("display","block");
			}

			if($("input:radio[name='product[has_buy_now]']:checked").val()=='1')
			{
				 $('#buy_area').css("display","block");
			}


		});
	</script>

<script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>

app/views/products/_product.html.erb
<div class="col-lg-3 col-md-4 col-sm-6">
  <div class="card">
    <img class="card-img-top" src="<%= product.coverimage.url(:medium) %>" alt="Card image cap">
    <div class="card-body">
      <h4 class="card-title"><%= product.name %></h4>
      <h6 class="card-subtitle mb-2 text-muted">Seller Name</h6>
      <p class="card-text"><%= product.description %></p>
      <p class="card-text">Auction price: <%= product.auction_price_start %></p>
      <a href="#" class="card-link">View Details</a>
    </div>
  </div>
</div>

app/views/products/_similar_item.html.erb
<section class="men-collection gray-bg">
  <div class="container">
    <header class="text-center">
      <h2 class="text-uppercase"><small>Similar Items</small>You may also like</h2>
    </header>
    <div class="row">
    <% if @products.length > 0 %>
      <% @products.each do |product| %>
      <div class="col-xl-3 col-md-4 col-sm-6">
        <div class="product is-gray">
          <div class="image d-flex align-items-center justify-content-center">
          <% if product.pictures.first %>
            <%= image_tag product.pictures.first.image.url, class: "img-fluid" %>
          <% else %>
            <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hoodie-man-1.png" alt="product" class="img-fluid">          
          <% end %>
            <div class="hover-overlay d-flex align-items-center justify-content-center">
              <div class="CTA d-flex align-items-center justify-content-center">
                <a href="#" class="add-to-cart">
                  <i class="fa fa-shopping-cart"></i>
                </a>
                <%= link_to detail_product_path(product), class: "visit-product active" do %>
                  <i class="icon-search"></i>
                  View
                <% end %>
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view">
                  <i class="fa fa-arrows-alt"></i>
                </a>
              </div>
            </div>
          </div>
          <div class="title">
            <%= link_to detail_product_path(product) do %>
              <h3 class="h6 text-uppercase no-margin-bottom"><%= product.name %></h3>
            <% end %>
            <span class="price text-muted">
              <% if product.price_for_buy %>
                  <% if product.price_for_buy > 0 %>
                    $<%= product.price_for_buy %>
                  <% else %>
                    Bid only
                  <% end %>
                <% end %>
              </span>
          </div>
        </div>
      </div>
      <% end %>
    <% else %>
      <p>No results found.</p>
    <% end %>
    </div>
  </div>
</section>

app/views/products/edit.html.erb
<section class="hero hero-page gray-bg padding-small">
	<div class="container">
		<h1>Edit Product</h1>
		<div class="row">
			<div class="col-xl-8 col-lg-10 col-md-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/products/index.html.erb
<section class="hero hero-home no-padding">
  <div class="owl-carousel owl-theme hero-slider">
    <div style="background: url(&quot;https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hero-bg-3.jpg&quot;);"
      class="item d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 text-white">
            <h1>DEAL WITH IT</h1>
            <p class="lead">
              You won't be able to resist all these offers
            </p>
            <a id="auction" class="btn btn-template wide shop-now">
              Explore Auction Feature
              <i class="icon-bag"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div style="background: url(&quot;https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hero-bg.jpg&quot;)"
      class="item d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h1>TREND MASTERCLASS</h1>
              <p class="lead">
                Get the look to turn heads in stylish pieces 
              </p>
              <a id="buynow" class="btn btn-template wide shop-now">
                Explore Buy Now Feature
                <i class="icon-bag"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div style="background: url(&quot;https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hero-bg-2.jpg&quot;); " 
           class="item d-flex align-items-center">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 text-white">
              <h1>SHOP SMART</h1>
              <p class="lead">
                Get ahead with the cleverest products around & free shipping
              </p>
              <a href="#" class="btn btn-template wide shop-now">
                Shop Now
                <i class="icon-bag"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <section class="categories">
    <div class="container">
      <header class="text-center">
        <h2 class="text-uppercase">
        <small>Top for this month</small>
        Our Featured Picks
        </h2>
      </header>
      <div class="row text-left">
        <div class="col-lg-4">
          <%= link_to category_path(@categories.fourth.name) do %>
            <div style="background-image: url(http://kinbechpokhara.com/wp-content/uploads/2017/06/samsung-galaxy-s8-plus.png);"
              class="item d-flex align-items-end">
              <div class="content">
                <h3 class="h5"><%= @categories.fourth.name %></h3>
                <span>New Collection</span>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-4">
          <%= link_to category_path(@categories.first.name) do %>
            <div style="background-image: url(https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/banner-2.jpg);"
              class="item d-flex lign-items-end">
              <div class="content">
                <h3 class="h5"><%= @categories.first.name %></h3>
                <span>New Collection</span>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-4">
          <%= link_to category_path(@categories.second.name) do %>
            <div style="background-image: url(https://png.pngtree.com/element_origin_min_pic/17/03/23/093b2407b7b8bcdd7f8b36066759b1fc.jpg);" class="item d-flex align-items-end">
              <div class="content">
                <h3 class="h5"><%= @categories.second.name %></h3>
                <span>Sale of 20%</span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>

  <%# Auction %>
  <section id="auction-section" class="men-collection gray-bg">
    <div class="container">
      <header class="text-center">
        <h2 class="text-uppercase">
          <small>Listing Auction</small>
          Our Collection
        </h2>
      </header>
      <div class="owl-carousel owl-theme products-slider">
        <% @auctions.each do |product| %>
        <div class="item">
          <div class="product is-gray">
            <div class="image d-flex align-items-center justify-content-center">
              <% if product.pictures.first %>
                <%= image_tag product.pictures.first.image.url, class: "img-fluid" %>
              <% else %>
                <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hoodie-man-1.png" alt="product" class="img-fluid">
              <% end %>
              <div class="hover-overlay d-flex align-items-center justify-content-center">
                <div class="CTA d-flex align-items-center justify-content-center">
                  <a href="#" class="add-to-cart">
                    <i class="fa fa-shopping-cart"></i>
                  </a>
                  <%= link_to detail_product_path(product), class: "visit-product active" do %>
                  <i class="icon-search"></i>
                  View
                  <% end %>
                  <a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view">
                    <i class="fa fa-arrows-alt"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="title">
              <%= link_to detail_product_path(product) do %>
              <h3 class="h6 text-uppercase no-margin-bottom"><%= product.name %></h3>
              <% end %>
              <span class="price text-muted">
                <% if product.price_for_buy %>
                  <% if product.price_for_buy > 0 %>
                    $<%= product.price_for_buy %>
                  <% else %>
                    Bid only
                  <% end %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </section>
  
  <%# Buynow %>
  <section id="buynow-section" class="men-collection gray-bg">
    <div class="container">
      <header class="text-center">
        <h2 class="text-uppercase">
          <small>Listing Buy Now</small>
          Our Collection
        </h2>
      </header>
      <div class="owl-carousel owl-theme products-slider">
        <% @buynows.each do |product| %>
        <div class="item">
          <div class="product is-gray">
            <div class="image d-flex align-items-center justify-content-center">
              <% if product.pictures.first %>
                <%= image_tag product.pictures.first.image.url, class: "img-fluid" %>
              <% else %>
                <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hoodie-man-1.png" alt="product" class="img-fluid">
              <% end %>
              <div class="hover-overlay d-flex align-items-center justify-content-center">
                <div class="CTA d-flex align-items-center justify-content-center">
                  <a href="#" class="add-to-cart">
                    <i class="fa fa-shopping-cart"></i>
                  </a>
                  <%= link_to detail_product_path(product), class: "visit-product active" do %>
                  <i class="icon-search"></i>
                  View
                  <% end %>
                  <a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view">
                    <i class="fa fa-arrows-alt"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="title">
              <%= link_to detail_product_path(product) do %>
              <h3 class="h6 text-uppercase no-margin-bottom"><%= product.name %></h3>
              <% end %>
              <span class="price text-muted">
                <% if product.price_for_buy %>
                  <% if product.price_for_buy > 0 %>
                    $<%= product.price_for_buy %>
                  <% else %>
                    Bid only
                  <% end %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </section>

app/views/products/new.html.erb
<section class="hero hero-page gray-bg padding-small">
	<div class="container">
		<h1>New Product</h1>
		<div class="row">
			<div class="col-xl-8 col-lg-10 col-md-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/products/search.html.erb
<section class="men-collection gray-bg">
  <div class="container">
    <header class="text-center">
      <h2 class="text-uppercase"><small>Resutl for </small> '<%= @params %>'</h2>
    </header>
    <div class="row">
    <% if @products.length > 0 %>
      <% @products.each do |product| %>
      <div class="col-xl-3 col-md-4 col-sm-6">
        <div class="product is-gray">
          <div class="image d-flex align-items-center justify-content-center">
          <% if product.pictures.first %>
            <%= image_tag product.pictures.first.image.url, class: "img-fluid" %>
          <% else %>
            <img src="https://d32d8xzgnjxuvk.cloudfront.net/hub/1-2/img/hoodie-man-1.png" alt="product" class="img-fluid">          
          <% end %>
            <div class="hover-overlay d-flex align-items-center justify-content-center">
              <div class="CTA d-flex align-items-center justify-content-center">
                <a href="#" class="add-to-cart">
                  <i class="fa fa-shopping-cart"></i>
                </a>
                <%= link_to detail_product_path(product), class: "visit-product active" do %>
                  <i class="icon-search"></i>
                  View
                <% end %>
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view">
                  <i class="fa fa-arrows-alt"></i>
                </a>
              </div>
            </div>
          </div>
          <div class="title">
            <%= link_to detail_product_path(product) do %>
              <h3 class="h6 text-uppercase no-margin-bottom"><%= product.name %></h3>
            <% end %>
            <span class="price text-muted">
              <% if product.price_for_buy %>
                  <% if product.price_for_buy > 0 %>
                    $<%= product.price_for_buy %>
                  <% else %>
                    Bid only
                  <% end %>
                <% end %>
              </span>
          </div>
        </div>
      </div>
      <% end %>
    <% else %>
      <p>No results found.</p>
    <% end %>
    </div>
  </div>
</section>

app/views/products/show.html.erb
   <br>
    <input type="hidden" id="productID" value="<%= @product.id %>">

  <div class="container" >
    <div class="row">
    <div class="col-sm-9 col-md-9">
      <h1 style="font-weight: bold">Product Detail -  <%= @product.name %></h1>
    </div>
   
    <div class="col-sm-3 col-md-3">
      
         <div class="form-actions">
       <!--    <%= link_to 'Back', product_path(), :class => 'btn btn-primary'  %> -->
          <a href="/" class="btn btn-primary">Back</a>
          <%= link_to 'Edit', edit_product_path(@product), :class => 'btn btn-warning' %>
          <%= link_to 'Delete', product_path(@product), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
        </div>
   
    </div>
  </div>
  </div>
    
<hr>

  <div class="container">
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Name</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= @product.name %>
      </div>
      
     
      
    </div>
     <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Category</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= @category.name %>
      </div>
      
     
      
    </div>
    <br>
     <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Condition</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <% if @product.condition==0 %>
          <p>Cũ</p>
        <% else %>
          <p>Mới</p>
        <% end %>
      
      </div> 
      
    </div>

    <br>
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Description</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= @product.description %>
      </div>
      
      
    </div>

    <br>
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Details</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= @product.details.html_safe  %>
      </div>
      
      
    </div>

<br>
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Date Add</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= @product.date_in  %>
      </div>
      
      
    </div>
<br>
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <b>Seller</b>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
       
        <a href="#"> <%= @seller.email  %></a>
      </div>
      
      
    </div>


<br>
     <div class="row">
      <div class="col-md-12">
        <b>Auction Infomation</b>
      </div>

      <ul>
        <li>Price for buy:  $<%= @product.price_for_buy %></li>
        <li>Price for auction:  $<%= @product.auction_price_start %></li>
        <li>Date end auction:  <%= @product.date_end_auction %></li>
      </ul>
      
    </div>

  <br>
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <b>List images</b>
      </div>
     
       <ul class="thumbnails files">
        <% unless @pictures.empty? %>
          <% @pictures.each do |pic| %>
            <li class="span3" id="picture_<%= pic.id %>">
            <div class="thumbnail">
              <%= image_tag pic.image.url,:style => "width:100%;" %>
              <div class="caption">

                <p style="text-align: center;">
               <!--  <%= link_to "Edit", picture_path(pic) %> -->

                <%=
                  link_to "Delete", pic,
                    :data => { :confirm => "Are you sure?" },
                    :method => :delete
                  %>

                </p>
              </div>
            </div>
            </li>
          <% end %>
        <% end %>
      </ul>
      
    </div>

  </div>
    